chore: fix build (digital envelope routines) (#837)
Fix the
[build](https://github.com/google-github-actions/release-please-action/actions/runs/6384766312/job/17328084659):

```
> release-please-action@3.7.12 build
> ncc build index.js

ncc: Version 0.27.0
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at hashOf (/home/runner/work/release-please-action/release-please-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3253134)
    at ncc (/home/runner/work/release-please-action/release-please-action/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:1:3256648)
    at runCmd (/home/runner/work/release-please-action/release-please-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:51537)
    at 819 (/home/runner/work/release-please-action/release-please-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:48344)
    at __webpack_require__ (/home/runner/work/release-please-action/release-please-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55043)
    at /home/runner/work/release-please-action/release-please-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55194
    at /home/runner/work/release-please-action/release-please-action/node_modules/@vercel/ncc/dist/ncc/cli.js.cache.js:1:55220
    at Object.<anonymous> (/home/runner/work/release-please-action/release-please-action/node_modules/@vercel/ncc/dist/ncc/cli.js:8:28) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

I think the problem is linked to the [Node version
upgrade](https://github.com/google-github-actions/release-please-action/pull/835)
and the [OpenSSL
version](https://nodejs.org/fr/blog/vulnerability/openssl-november-2022).
The `@vercel/ncc` upgrade fixes the problem because they
[replaced](https://github.com/vercel/ncc/pull/868) a deprecated hash
algorithm with _sha256_.